nix:
  enable: false
  packages: [zlib zlib.dev]

flags:
  gitit:
    plugins: true
packages:
- '.'
extra-deps:
- commonmark-0.2.1
- commonmark-pandoc-0.2.1.1
- skylighting-core-0.11
- skylighting-0.11
- doctemplates-0.10
- citeproc-0.4.1
- ConfigFile-1.1.4
- filestore-0.6.5
- recaptcha-0.1.0.4
- MissingH-1.4.3.0
- json-0.10
allow-newer: true
resolver: lts-18.0
